name = "eventcheck-frontend"
compatibility_date = "2026-09-01"

main = "./worker.js"

[assets]
directory = "./dist"
not_found_handling = "single-page-application"

[vars]
BACKEND_URL = "https://natural-beauty-production-5cb5.up.railway.app"
