// RaaS Phase 0 — Granular permission catalogue + default role mappings.
// Spec §10-13, §72: one authorization engine. Roles are configuration.
// Permission format: <resource>.<action>, e.g. guest.view, checkin.perform.

export const PERMISSIONS = [
  'guest.view',
  'guest.create',
  'guest.update',
  'guest.delete',
  'invite.view',
  'invite.create',
  'invite.revoke',
  'rsvp.view',
  'rsvp.create',
  'rsvp.update',
  'rsvp.override',
  'rsvp.export',
  'checkin.view',
  'checkin.perform',
  'checkin.override',
  'seating.view',
  'seating.assign',
  'seating.update',
  'incident.view',
  'incident.create',
  'incident.assign',
  'incident.resolve',
  'order.view',
  'order.create',
  'order.update',
  'order.fulfill',
  'service_request.view',
  'service_request.create',
  'service_request.assign',
  'service_request.fulfill',
  'vendor.view',
  'vendor.manage',
  'transport.view',
  'transport.assign',
  'transport.update',
  'transport.manage',
  'accommodation.view',
  'accommodation.manage',
  'event.view',
  'event.update',
  'event.close',
  'event.delete',
  'staff.view',
  'staff.assign',
  'staff.update',
  'task.view',
  'task.create',
  'task.assign',
  'task.update',
  'task.complete',
  'schedule.view',
  'schedule.manage',
  'report.view',
  'audit.view',
  'template.view',
  'template.manage',
  'venue.view',
  'venue.manage',
  'contract.view',
  'contract.manage',
  'org.view',
  'org.manage',
];

// Configurable event-level roles. Platform roles (admin/staff in users.role)
// remain; these role_keys scope what a user can do WITHIN one event.
export const EVENT_ROLES = [
  'event_owner',
  'event_manager',
  'raas_operator',
  'checkin_staff',
  'security',
  'usher',
  'waiter',
  'kitchen',
  'bar',
  'driver',
  'transport_coordinator',
  'sound',
  'performer',
  'photographer',
  'vendor',
  'speaker',
  'vip_coordinator',
];

const ALL = [...PERMISSIONS];

export const DEFAULT_ROLE_PERMISSIONS = {
  event_owner: ALL,
  event_manager: [
    'guest.view', 'guest.create', 'guest.update',
    'invite.view', 'invite.create', 'invite.revoke',
    'rsvp.view', 'rsvp.create', 'rsvp.update', 'rsvp.override', 'rsvp.export',
    'checkin.view', 'checkin.perform', 'checkin.override',
    'seating.view', 'seating.assign', 'seating.update',
    'incident.view', 'incident.create', 'incident.assign', 'incident.update', 'incident.resolve',
    'order.view', 'order.create', 'order.update', 'order.fulfill',
    'service_request.view', 'service_request.create', 'service_request.assign', 'service_request.fulfill',
    'vendor.view', 'vendor.manage',
    'transport.view', 'transport.assign', 'transport.update', 'transport.manage',
    'accommodation.view', 'accommodation.manage',
    'task.view', 'task.create', 'task.assign', 'task.update', 'task.complete',
    'schedule.view', 'schedule.manage',
    'event.view', 'event.update',
    'staff.view', 'staff.assign', 'staff.update',
    'venue.view', 'venue.manage',
    'report.view',
  ],
  raas_operator: [
    'guest.view', 'guest.create', 'guest.update',
    'invite.view', 'invite.create', 'invite.revoke',
    'rsvp.view', 'rsvp.create', 'rsvp.update', 'rsvp.override', 'rsvp.export',
    'checkin.view', 'checkin.perform', 'checkin.override',
    'seating.view', 'seating.assign',
    'incident.view', 'incident.create', 'incident.assign', 'incident.update', 'incident.resolve',
    'order.view', 'order.update', 'order.fulfill',
    'service_request.view', 'service_request.create', 'service_request.assign', 'service_request.fulfill',
    'vendor.view', 'vendor.manage',
    'transport.view', 'transport.assign', 'transport.update', 'transport.manage',
    'accommodation.view', 'accommodation.manage',
    'task.view', 'task.create', 'task.assign', 'task.update', 'task.complete',
    'schedule.view', 'schedule.manage',
    'event.view', 'event.update', 'event.close',
    'staff.view', 'staff.assign', 'staff.update',
    'venue.view', 'venue.manage',
    'contract.view', 'contract.manage',
    'template.view', 'template.manage',
    'org.view',
    'report.view', 'audit.view',
  ],
  checkin_staff: ['guest.view', 'guest.create', 'checkin.view', 'checkin.perform', 'event.view', 'rsvp.view', 'task.view'],
  security: ['guest.view', 'checkin.view', 'incident.view', 'incident.create', 'incident.update', 'event.view', 'rsvp.view', 'task.view'],
  usher: ['guest.view', 'checkin.view', 'seating.view', 'event.view', 'rsvp.view', 'task.view', 'service_request.view', 'service_request.create'],
  waiter: ['order.view', 'order.create', 'seating.view', 'event.view', 'task.view', 'service_request.view', 'service_request.create', 'service_request.fulfill'],
  kitchen: ['order.view', 'order.update', 'order.fulfill', 'event.view', 'task.view', 'service_request.view', 'service_request.fulfill'],
  bar: ['order.view', 'order.update', 'order.fulfill', 'event.view', 'task.view'],
  driver: ['transport.view', 'event.view', 'task.view'],
  transport_coordinator: ['transport.view', 'transport.assign', 'transport.update', 'transport.manage', 'guest.view', 'event.view', 'task.view', 'task.assign'],
  sound: ['event.view', 'task.view'],
  performer: ['event.view', 'task.view'],
  photographer: ['event.view', 'task.view'],
  vendor: ['event.view', 'vendor.view', 'task.view'],
  speaker: ['event.view', 'task.view'],
  vip_coordinator: ['guest.view', 'seating.view', 'seating.assign', 'transport.view', 'event.view', 'rsvp.view', 'task.view', 'service_request.view'],
};

// Legacy platform mapping (users.role) → baseline permissions when no
// event-specific role row exists. Preserves v1 behavior while Phase 0
// introduces granular checks.
export const PLATFORM_BASELINE = {
  admin: ALL,
  staff: ['guest.view', 'guest.create', 'checkin.view', 'checkin.perform', 'event.view', 'report.view', 'task.view'],
};

export function defaultPermissionsForRole(roleKey) {
  return DEFAULT_ROLE_PERMISSIONS[roleKey] || [];
}
