// RaaS Phase 0 — Event templates as configuration over the universal engine.
// Spec §10, §28, §83: adding a template must NOT require rebuilding the core.

export const EVENT_TEMPLATES = [
  {
    key: 'wedding',
    name: 'Wedding',
    description: 'Wedding reception with invitations, seating, service and gifts.',
    default_modules: ['guests', 'invitations', 'rsvp', 'checkin', 'seating', 'schedule', 'announcements', 'food_service', 'transport', 'gifts', 'guestbook', 'gallery', 'reporting', 'command'],
    default_roles: ['event_owner', 'event_manager', 'raas_operator', 'checkin_staff', 'security', 'usher', 'waiter', 'kitchen', 'bar', 'driver', 'photographer', 'vip_coordinator'],
    terminology: { guests: 'Guests', checkin: 'Check-in', seating: 'Seating' },
    default_settings: { onboarding_method: 'approval', rsvp_enabled: true, seating_enabled: true, gifts_enabled: true },
  },
  {
    key: 'introduction',
    name: 'Introduction / Traditional Wedding',
    description: 'Traditional introduction ceremony.',
    default_modules: ['guests', 'invitations', 'rsvp', 'checkin', 'seating', 'announcements', 'food_service', 'gifts', 'reporting'],
    default_roles: ['event_owner', 'event_manager', 'checkin_staff', 'security', 'usher', 'vip_coordinator'],
    terminology: { guests: 'Guests', checkin: 'Check-in' },
    default_settings: { onboarding_method: 'approval', rsvp_enabled: true, seating_enabled: true },
  },
  {
    key: 'private_celebration',
    name: 'Private Celebration',
    description: 'Default simple event: birthdays, family gatherings.',
    default_modules: ['guests', 'invitations', 'rsvp', 'checkin', 'announcements', 'reporting'],
    default_roles: ['event_owner', 'event_manager', 'checkin_staff', 'security'],
    terminology: { guests: 'Guests', checkin: 'Check-in' },
    default_settings: { onboarding_method: 'approval', rsvp_enabled: true },
  },
  {
    key: 'corporate_dinner',
    name: 'Corporate Dinner',
    description: 'Seated corporate dinner with VIP handling.',
    default_modules: ['guests', 'invitations', 'rsvp', 'checkin', 'seating', 'schedule', 'announcements', 'food_service', 'transport', 'reporting', 'command'],
    default_roles: ['event_owner', 'event_manager', 'raas_operator', 'checkin_staff', 'security', 'usher', 'waiter', 'driver', 'vip_coordinator'],
    terminology: { guests: 'Guests', checkin: 'Registration' },
    default_settings: { onboarding_method: 'approval', rsvp_enabled: true, seating_enabled: true },
  },
  {
    key: 'corporate_event',
    name: 'Corporate Event',
    description: 'General corporate gathering.',
    default_modules: ['guests', 'registration', 'checkin', 'schedule', 'announcements', 'reporting', 'command'],
    default_roles: ['event_owner', 'event_manager', 'checkin_staff', 'security', 'usher'],
    terminology: { guests: 'Attendees', checkin: 'Registration' },
    default_settings: { onboarding_method: 'approval' },
  },
  {
    key: 'conference',
    name: 'Conference',
    description: 'Multi-session conference with speakers and badges.',
    default_modules: ['guests', 'registration', 'checkin', 'schedule', 'speakers', 'announcements', 'feedback', 'reporting', 'command'],
    default_roles: ['event_owner', 'event_manager', 'raas_operator', 'checkin_staff', 'security', 'usher', 'speaker', 'vendor'],
    terminology: { guests: 'Attendees', checkin: 'Registration' },
    default_settings: { onboarding_method: 'auto_approve' },
  },
  {
    key: 'graduation',
    name: 'Graduation',
    description: 'Graduation ceremony with large attendance.',
    default_modules: ['guests', 'registration', 'checkin', 'seating', 'schedule', 'announcements', 'reporting'],
    default_roles: ['event_owner', 'event_manager', 'checkin_staff', 'security', 'usher'],
    terminology: { guests: 'Guests', checkin: 'Check-in' },
    default_settings: { onboarding_method: 'approval' },
  },
  {
    key: 'religious_event',
    name: 'Religious Event',
    description: 'Church / mosque / religious gathering.',
    default_modules: ['guests', 'registration', 'checkin', 'announcements', 'reporting'],
    default_roles: ['event_owner', 'event_manager', 'checkin_staff', 'usher'],
    terminology: { guests: 'Members', checkin: 'Check-in' },
    default_settings: { onboarding_method: 'auto_approve' },
  },
  {
    key: 'awards',
    name: 'Awards',
    description: 'Awards night with VIP seating.',
    default_modules: ['guests', 'invitations', 'rsvp', 'checkin', 'seating', 'schedule', 'announcements', 'reporting'],
    default_roles: ['event_owner', 'event_manager', 'checkin_staff', 'security', 'usher', 'vip_coordinator'],
    terminology: { guests: 'Guests', checkin: 'Check-in' },
    default_settings: { onboarding_method: 'approval' },
  },
  {
    key: 'networking',
    name: 'Networking',
    description: 'Networking mixer.',
    default_modules: ['guests', 'registration', 'checkin', 'announcements', 'reporting'],
    default_roles: ['event_owner', 'event_manager', 'checkin_staff'],
    terminology: { guests: 'Attendees', checkin: 'Check-in' },
    default_settings: { onboarding_method: 'auto_approve' },
  },
  {
    key: 'fundraiser',
    name: 'Fundraiser',
    description: 'Fundraising dinner / charity event.',
    default_modules: ['guests', 'invitations', 'rsvp', 'checkin', 'donations', 'announcements', 'reporting'],
    default_roles: ['event_owner', 'event_manager', 'checkin_staff', 'security', 'usher'],
    terminology: { guests: 'Donors', checkin: 'Check-in' },
    default_settings: { onboarding_method: 'approval' },
  },
  {
    key: 'workshop',
    name: 'Workshop',
    description: 'Training workshop with sessions.',
    default_modules: ['guests', 'registration', 'checkin', 'schedule', 'announcements', 'feedback', 'reporting'],
    default_roles: ['event_owner', 'event_manager', 'checkin_staff', 'speaker'],
    terminology: { guests: 'Participants', checkin: 'Registration' },
    default_settings: { onboarding_method: 'auto_approve' },
  },
  {
    key: 'retreat',
    name: 'Retreat',
    description: 'Multi-session retreat with accommodation + transport.',
    default_modules: ['guests', 'registration', 'checkin', 'schedule', 'accommodation', 'transport', 'announcements', 'reporting'],
    default_roles: ['event_owner', 'event_manager', 'checkin_staff', 'driver', 'transport_coordinator'],
    terminology: { guests: 'Participants', checkin: 'Check-in' },
    default_settings: { onboarding_method: 'approval' },
  },
  {
    key: 'product_event',
    name: 'Product / Brand Event',
    description: 'Launch / brand activation.',
    default_modules: ['guests', 'registration', 'checkin', 'announcements', 'gallery', 'reporting'],
    default_roles: ['event_owner', 'event_manager', 'checkin_staff', 'security', 'vendor'],
    terminology: { guests: 'Guests', checkin: 'Check-in' },
    default_settings: { onboarding_method: 'auto_approve' },
  },
];
